= Support

Projectile currently has several official & unofficial support channels.

For questions, suggestions and support refer to one of them.  Please, don't
use the support channels to report issues, as this makes them harder to track.

== Gitter

Most internal discussions about the development of Projectile happen on its
https://gitter.im/bbatsov/projectile[gitter channel].  You can often find
Projectile's maintainers there and get some interesting news from the project's
kitchen.

== Mailing List

The https://groups.google.com/forum/#!forum/projectile[official mailing list] is
hosted at Google Groups. It's a low-traffic list, so don't be too hesitant to subscribe.

== Freenode

If you're into IRC you can visit the `#projectile` channel on Freenode.
It's not actively
monitored by the Projectile maintainers themselves, but still you can get support
from other Projectile users there.

== Stackoverflow

We're also encouraging users to ask Projectile-related questions on StackOverflow.

When doing so you should use the
http://stackoverflow.com/questions/tagged/projectile[Projectile] tag (ideally combined
with the tag `emacs`).

== Bountysource

If you're willing to pay for some feature to be implemented you can use
https://www.bountysource.com/teams/projectile/issues[Bountysource] to place a
bounty for the work you want to be done.
